name: 🚀 機能リクエスト
description: アイデア、新機能、改善案を提案する
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        アイデアの提案ありがとうございます。galjp をより良くするために役立ちます。
  - type: textarea
    attributes:
      label: 提案する機能は何ですか？
      description: 実現したいことを明確に説明してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: なぜこの機能が必要ですか？
      description: どのような用途で使いたいか、あるいはどんな課題を解決するかを説明してください。
