/**
 * Generate the "legible set" — characters a reader recognises on sight.
 *
 * We use JIS X 0208 (levels 1 and 2). §6.3 of docs/DESIGN.md: recursion stops
 * at a component only if that component is legible on its own, which is what
 * separates 語→言吾 (吾 is JIS X 0208) from 倍→ｲ立ﾛ (咅 is not).
 *
 * No dependency needed: Node's TextDecoder speaks shift_jis. We restrict lead
 * bytes to 0x88–0xEA so the CP932 NEC/IBM extension rows stay out.
 */
import { writeFileSync } from 'node:fs';

const OUT = 'data/legible.tsv';

const decoder = new TextDecoder('shift_jis', { fatal: false });
const chars = new Set<string>();

for (let hi = 0x88; hi <= 0xea; hi++) {
  for (let lo = 0x40; lo <= 0xfc; lo++) {
    if (lo === 0x7f) continue;
    const s = decoder.decode(new Uint8Array([hi, lo]));
    if (s.length !== 1 || s === '�') continue;
    if (!/\p{Script=Han}/u.test(s)) continue;
    chars.add(s);
  }
}

const sorted = [...chars].sort((a, b) => a.codePointAt(0)! - b.codePointAt(0)!);

writeFileSync(
  OUT,
  [
    '# JIS X 0208 levels 1-2 kanji, one per line.',
    '# Generated by scripts/build-legible.ts — do not edit.',
    ...sorted,
  ].join('\n') + '\n',
  'utf8',
);

console.log(`wrote ${OUT}: ${sorted.length} kanji`);
for (const probe of ['吾', '咅', '信', '龠']) {
  console.log(`  ${probe}: ${chars.has(probe) ? 'legible' : 'not legible'}`);
}
