/**
 * KanjiVG XML -> data/structure.tsv
 *
 * Run `npm run data:fetch` first to populate .cache/kanjivg.xml.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { buildStructureMap, formatIds } from './lib/kanjivg.ts';

const SRC = '.cache/kanjivg.xml';
const OUT = 'data/structure.tsv';

if (!existsSync(SRC)) {
  console.error(`missing ${SRC} — run: npm run data:fetch`);
  process.exit(1);
}

const map = buildStructureMap(readFileSync(SRC, 'utf8'));

const rows = [...map.entries()]
  .filter(([ch]) => [...ch].length === 1)
  .sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);

const lines = [
  '# char\tIDS',
  '# Generated by scripts/extract-structure.ts — do not edit.',
  '# Derived from KanjiVG (c) Ulrich Apel, CC BY-SA 3.0 — https://kanjivg.tagaini.net/',
  ...rows.map(([ch, s]) => `${ch}\t${formatIds(s)}`),
];
writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');

const byOp = new Map<string, number>();
for (const [, s] of rows) byOp.set(s.operator, (byOp.get(s.operator) ?? 0) + 1);

console.log(`wrote ${OUT}: ${rows.length} entries`);
for (const [op, n] of [...byOp].sort((a, b) => b[1] - a[1])) {
  console.log(`  ${op} ${n}`);
}
