/**
 * Unihan -> data/variant.tsv (学 -> 學) and data/joyo.tsv.
 *
 * Unihan's variant fields describe *Chinese* relationships, so they need heavy
 * filtering before they mean anything in Japanese. `kTraditionalVariant` maps
 * simplified to traditional, and where simplification merged several
 * characters the result is nonsense for Japanese: 丑→醜, 云→雲, 出→齣, 千→韆.
 *
 * The filters below keep only pairs that behave like a genuine 新字体→旧字体
 * relationship, and data/variant-block.ts removes the handful that still slip
 * through. The result is small enough (81 pairs) that every one has been read
 * by eye, which is why `variant` is safe to enable by default.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { unzipEntry } from './lib/unzip.ts';
import { variantBlock } from '../data/variant-block.ts';

const ZIP = '.cache/Unihan.zip';
const OUT = 'data/variant.tsv';
const JOYO_OUT = 'data/joyo.tsv';

if (!existsSync(ZIP)) {
  console.error(`missing ${ZIP} — run: npm run data:fetch`);
  process.exit(1);
}

const zip = readFileSync(ZIP);
const variantsFile = unzipEntry(zip, 'Unihan_Variants.txt').toString('utf8');
const irgFile = unzipEntry(zip, 'Unihan_IRGSources.txt').toString('utf8');
const otherFile = unzipEntry(zip, 'Unihan_OtherMappings.txt').toString('utf8');

const charOf = (code: string): string => String.fromCodePoint(parseInt(code.slice(2), 16));

const legible = new Set(
  readFileSync('data/legible.tsv', 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#'))
    .join(''),
);

// ---- 常用漢字 -------------------------------------------------------------
const joyo = new Set<string>();
for (const line of otherFile.split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [code, field] = line.split('\t');
  if (field === 'kJoyoKanji' && code) joyo.add(charOf(code));
}

// ---- stroke counts --------------------------------------------------------
const strokes = new Map<string, number>();
for (const line of irgFile.split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [code, field, value] = line.split('\t');
  if (field !== 'kTotalStrokes' || !code || !value) continue;
  const n = parseInt(value.split(' ')[0]!, 10);
  if (Number.isFinite(n)) strokes.set(charOf(code), n);
}

// ---- traditional variants -------------------------------------------------
const blocked = new Set(variantBlock);
const rejected: string[] = [];
const pairs = new Map<string, string>();

for (const line of variantsFile.split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [code, field, value] = line.split('\t');
  if (field !== 'kTraditionalVariant' || !code || !value) continue;

  const from = charOf(code);
  // Only characters people actually type.
  if (!joyo.has(from)) continue;

  const targets = value
    .trim()
    .split(/\s+/)
    .map((t) => /^U\+([0-9A-Fa-f]+)/.exec(t))
    .filter((m): m is RegExpExecArray => m !== null)
    .map((m) => String.fromCodePoint(parseInt(m[1]!, 16)))
    .filter((to) => to !== from);

  // A merged simplification offers several unrelated traditional forms; a real
  // 新字体 offers exactly one old form.
  if (targets.length !== 1) {
    rejected.push(`${from} -> ${targets.join('/')} (ambiguous)`);
    continue;
  }
  const to = targets[0]!;

  // 丑→醜, 云→雲: the "old form" is itself an everyday character, which means
  // the two are separate words in Japanese rather than two spellings of one.
  if (joyo.has(to)) {
    rejected.push(`${from} -> ${to} (target is joyo)`);
    continue;
  }
  if (!legible.has(to)) {
    rejected.push(`${from} -> ${to} (target outside JIS X 0208)`);
    continue;
  }

  const a = strokes.get(from);
  const b = strokes.get(to);
  // Old forms are more elaborate, never simpler.
  if (a === undefined || b === undefined || b <= a) {
    rejected.push(`${from} -> ${to} (stroke count ${a} -> ${b})`);
    continue;
  }

  if (blocked.has(from)) {
    rejected.push(`${from} -> ${to} (hand-blocked, see data/variant-block.ts)`);
    continue;
  }

  pairs.set(from, to);
}

const rows = [...pairs.entries()].sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);

writeFileSync(
  OUT,
  [
    '# char\tvariant\tsource-field',
    '# Generated by scripts/extract-variant.ts — do not edit.',
    '# Derived from the Unicode Character Database (c) Unicode, Inc.',
    ...rows.map(([from, to]) => `${from}\t${to}\tkTraditionalVariant`),
  ].join('\n') + '\n',
  'utf8',
);

const joyoSorted = [...joyo].sort((a, b) => a.codePointAt(0)! - b.codePointAt(0)!);
writeFileSync(
  JOYO_OUT,
  [
    '# 常用漢字 (kJoyoKanji), one per line.',
    '# Generated by scripts/extract-variant.ts — do not edit.',
    ...joyoSorted,
  ].join('\n') + '\n',
  'utf8',
);

console.log(`wrote ${OUT}: ${rows.length} pairs (from ${joyo.size} joyo kanji)`);
console.log(`wrote ${JOYO_OUT}: ${joyoSorted.length} kanji`);
console.log(`rejected ${rejected.length} candidate pairs`);
console.log(
  'accepted sample:',
  rows
    .slice(0, 30)
    .map(([a, b]) => `${a}→${b}`)
    .join(' '),
);
console.log('rejected sample:', rejected.slice(0, 12).join(', '));
